name: flutter_exercise
description: "An exercise project"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  #Architecture
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  #Data
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dio: ^5.7.0
  retrofit: ^4.4.0

  #Platform
  go_router: ^14.6.3
  flutter_secure_storage: ^9.2.4

  #UI
  cupertino_icons: ^1.0.8

  #Utils
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Architecture
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14

  #Data
  freezed: ^2.5.8
  json_serializable: ^6.9.2
  retrofit_generator: ">=8.0.0 <10.0.0"

  #Linter
  flutter_lints: ^4.0.0
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4

  #Testing
  mockito: ^5.4.5
  
flutter:
  uses-material-design: true
